rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - ruby-head
  - rbx-2.0
notifications:
  # overriding this so that TST Media's email account doesn't get spammed
  # feel free to add yourselves if you want in on this action
  email:
    - patrick.byrne@tstmedia.com
